### ISSUE TITLE
Support SocketCluster

### ISSUE THREAD

**Issue by IngwiePhoenix** [gigerlin/rpc#1]
I am actively using `avs-rpc` in my code but I just switched my backend to utilize http://socketcluster.io instead. But to test things, I ran this module inside of my code and tested the output. Turns out that there is only a minor change to do, and it would be supported flawlessly!

https://github.com/TopCloud/socketcluster/issues/65

According to this, all that needs to be changed is a callback that is aware of having two, instead of one, parameter.

I am not a big CoffeeScript user, so I probably won't be able to modify the required sources to make it work...

Kind regards,
Ingwie

**Comment by gigerlin** [comment]
Hi Ingwie,

I am glad that you are using avs-rpc. I think I know what the problem is looking at the TopCloud thread. I may create a scRpc class to handle that. Anyway, I will let you know when it is fixed.

Kind regards,
Gilles

**Comment by gigerlin** [comment]
Hi Ingwie,

You may try rpc = avs.scRpc(socket); I haven't tested it yet so give it a try and let me know if that works.

Regards, Gilles

**Comment by IngwiePhoenix** [comment]
Okay I am going to give it a try right now! :)

**Comment by IngwiePhoenix** [comment]
The rpc instance works fine, however, I still see the error event receiving the return value.

``` javascript
        socket = socketCluster.connect();
        rpc = new avs.scRpc(socket);
        socket.on('error', function (err) {
            console.log("Error:", err);
        });
        socket.on('connect', function () {
            console.log('CONNECTED');
            socket.on("rpc_init_data", function(methods){
                console.log("Methods: "+methods);
                rpcr = rpc.remote.call(rpc, methods);
                console.log("call", rpcr.foo({baz:"bar"}));
            });
            socket.emit("rpc_init");
        });
```

```
CONNECTED
Methods: foo
rpc 034378-1: out rpc {"method":"foo","args":[{"baz":"bar"}],"id":"034378-1"}
call undefined
Error: Object {0: Object, 1: Object}
```

```
rpc methods found: foo
rpc methods found: 
rpc 034378-1: in  rpc {"method":"foo","args":[{"baz":"bar"}],"id":"034378-1"}
rpc 034378-1: executing local foo - asynchronous: false
```

**Comment by gigerlin** [comment]
Hi Ingwie,

On the B side (the one printing rpc 034378-1: in  rpc {"method":"foo","args":[{"baz":"bar"}],"id":"034378-1"}), the rpc object must be a scRpc object as well. Could you post the code of side B?

Kind regards,
Gilles

**Comment by IngwiePhoenix** [comment]
Ouch, I am such a derp. :) Changing the avs.ioRpc to avs.scRpc made it magically work! Thank you a lot for making this work!

**Comment by gigerlin** [comment]
Cool, I'm glad everything's fine :-)
